const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tlauncher', {
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: (name) => ipcRenderer.invoke('accounts:add', name),
  accountsMicrosoft: () => ipcRenderer.invoke('accounts:microsoft-login'),
  accountsRemove: (id) => ipcRenderer.invoke('accounts:remove', id),
  accountsSuggestNames: (opts) => ipcRenderer.invoke('accounts:suggest-names', opts || {}),
  skinGet: (name) => ipcRenderer.invoke('skin:get', name),
  worldsList: (gameDir) => ipcRenderer.invoke('worlds:list', gameDir),
  worldsBackup: (p) => ipcRenderer.invoke('worlds:backup', p),
  worldsRestore: (p) => ipcRenderer.invoke('worlds:restore', p),
  worldsDelete: (p) => ipcRenderer.invoke('worlds:delete', p),
  serverStatus: (host) => ipcRenderer.invoke('server:status', { host }),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  diagRun: () => ipcRenderer.invoke('diag:run'),
  linkOpen: (url) => ipcRenderer.invoke('link:open', url),
  clientStatus: (gameDir) => ipcRenderer.invoke('client:status', gameDir),
  clientInstall: (p) => ipcRenderer.invoke('client:install', p),
  clientUpdate: (p) => ipcRenderer.invoke('client:update', p),
  clientProfiles: (gameDir) => ipcRenderer.invoke('client:profiles', gameDir),
  clientProfileSet: (p) => ipcRenderer.invoke('client:profile-set', p),
  presenceUpdate: (p) => ipcRenderer.invoke('presence:update', p || {}),
  presenceStatus: () => ipcRenderer.invoke('presence:status'),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSave: (s) => ipcRenderer.invoke('settings:save', s),
  javaList: (version) => ipcRenderer.invoke('java:list', version),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  pickDir: (current) => ipcRenderer.invoke('dialog:pick-dir', current),
  pickJava: () => ipcRenderer.invoke('dialog:pick-java'),
  versionsList: (opts) => ipcRenderer.invoke('versions:list', opts || {}),
  versionsUninstall: (p) => ipcRenderer.invoke('versions:uninstall', p),
  modsList: (gameDir) => ipcRenderer.invoke('mods:list', gameDir),
  modsToggle: (p) => ipcRenderer.invoke('mods:toggle', p),
  modsSearch: (q) => ipcRenderer.invoke('mods:search', q),
  modsVersions: (p) => ipcRenderer.invoke('mods:project-versions', p),
  modsDownload: (p) => ipcRenderer.invoke('mods:download', p),
  modsDelete: (p) => ipcRenderer.invoke('mods:delete', p),
  modsCheck: (p) => ipcRenderer.invoke('mods:check', p),
  loaderInstall: (p) => ipcRenderer.invoke('loader:install', p),
  modsImportJar: (gameDir) => ipcRenderer.invoke('mods:import-jar', gameDir),
  folderOpen: (dir) => ipcRenderer.invoke('folder:open', dir),
  launch: (payload) => ipcRenderer.invoke('game:launch', payload),
  killGame: () => ipcRenderer.invoke('game:kill'),
  isGameRunning: () => ipcRenderer.invoke('game:is-running'),
  onLog: (cb) => ipcRenderer.on('game:log', (_, msg) => cb(msg)),
  onProgress: (cb) => ipcRenderer.on('game:progress', (_, p) => cb(p)),
  onGameStarted: (cb) => ipcRenderer.on('game:started', () => cb()),
  onGameClosed: (cb) => ipcRenderer.on('game:closed', (_, code) => cb(code)),
  winMin: () => ipcRenderer.invoke('window:min'),
  winMax: () => ipcRenderer.invoke('window:max'),
  winClose: () => ipcRenderer.invoke('window:close'),
});
// New brand alias — renderer may use either window.cinder or window.tlauncher.
contextBridge.exposeInMainWorld('cinder', {
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: (name) => ipcRenderer.invoke('accounts:add', name),
  accountsMicrosoft: () => ipcRenderer.invoke('accounts:microsoft-login'),
  accountsRemove: (id) => ipcRenderer.invoke('accounts:remove', id),
  accountsSuggestNames: (opts) => ipcRenderer.invoke('accounts:suggest-names', opts || {}),
  skinGet: (name) => ipcRenderer.invoke('skin:get', name),
  worldsList: (gameDir) => ipcRenderer.invoke('worlds:list', gameDir),
  worldsBackup: (p) => ipcRenderer.invoke('worlds:backup', p),
  worldsRestore: (p) => ipcRenderer.invoke('worlds:restore', p),
  worldsDelete: (p) => ipcRenderer.invoke('worlds:delete', p),
  serverStatus: (host) => ipcRenderer.invoke('server:status', { host }),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  diagRun: () => ipcRenderer.invoke('diag:run'),
  linkOpen: (url) => ipcRenderer.invoke('link:open', url),
  clientStatus: (gameDir) => ipcRenderer.invoke('client:status', gameDir),
  clientInstall: (p) => ipcRenderer.invoke('client:install', p),
  clientUpdate: (p) => ipcRenderer.invoke('client:update', p),
  clientProfiles: (gameDir) => ipcRenderer.invoke('client:profiles', gameDir),
  clientProfileSet: (p) => ipcRenderer.invoke('client:profile-set', p),
  presenceUpdate: (p) => ipcRenderer.invoke('presence:update', p || {}),
  presenceStatus: () => ipcRenderer.invoke('presence:status'),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSave: (s) => ipcRenderer.invoke('settings:save', s),
  javaList: (version) => ipcRenderer.invoke('java:list', version),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  pickDir: (current) => ipcRenderer.invoke('dialog:pick-dir', current),
  pickJava: () => ipcRenderer.invoke('dialog:pick-java'),
  versionsList: (opts) => ipcRenderer.invoke('versions:list', opts || {}),
  versionsUninstall: (p) => ipcRenderer.invoke('versions:uninstall', p),
  modsList: (gameDir) => ipcRenderer.invoke('mods:list', gameDir),
  modsToggle: (p) => ipcRenderer.invoke('mods:toggle', p),
  modsSearch: (q) => ipcRenderer.invoke('mods:search', q),
  modsVersions: (p) => ipcRenderer.invoke('mods:project-versions', p),
  modsDownload: (p) => ipcRenderer.invoke('mods:download', p),
  modsDelete: (p) => ipcRenderer.invoke('mods:delete', p),
  modsCheck: (p) => ipcRenderer.invoke('mods:check', p),
  loaderInstall: (p) => ipcRenderer.invoke('loader:install', p),
  modsImportJar: (gameDir) => ipcRenderer.invoke('mods:import-jar', gameDir),
  folderOpen: (dir) => ipcRenderer.invoke('folder:open', dir),
  launch: (payload) => ipcRenderer.invoke('game:launch', payload),
  killGame: () => ipcRenderer.invoke('game:kill'),
  isGameRunning: () => ipcRenderer.invoke('game:is-running'),
  onLog: (cb) => ipcRenderer.on('game:log', (_, msg) => cb(msg)),
  onProgress: (cb) => ipcRenderer.on('game:progress', (_, p) => cb(p)),
  onGameStarted: (cb) => ipcRenderer.on('game:started', () => cb()),
  onGameClosed: (cb) => ipcRenderer.on('game:closed', (_, code) => cb(code)),
  winMin: () => ipcRenderer.invoke('window:min'),
  winMax: () => ipcRenderer.invoke('window:max'),
  winClose: () => ipcRenderer.invoke('window:close'),
});
